
name: 'dbt_Training'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
# on-run-start: "remove @s3unload pattern='.*Pricing.*'"
# on-run-end: "copy into @s3unload/Pricing.gz from ANALYTICS.SCH_LTI.PRICING_SUMMARY overwrite=true single=true"

models:
  dbt_Training:
    stage:
      materialized: view
    marts:
      materialized: table
tests:
  +store_failures: true
  +schema: failed
